ON_PI: True

SERVER:
  HOST: 0.0.0.0
  PORT: 5000

MOTOR_DRIVER:
  POWER_PIN: 17
  I2C_ID: 6
  ADDRESS: 0x53
  MOTORS:
    LEFT: 3
    RIGHT: 4

CAMERA:
  WIDTH: 64
  HEIGHT: 64
  CROPPED_WIDTH: 64
  CROPPED_HEIGHT: 32
